### ISSUE TITLE
Show if the repo is found on alioth or salsa

### ISSUE THREAD

**Issue by shanavas786** [LeoIannacone/npm2deb#104]
Thanks to @simevo npm2deb now searches for repositories on salsa too #102 . But the output doesn't says anything about if the repo was found in salsa or alioth.

**Comment by simevo** [comment]
After 2018-05-31, alioth will go offline so you should only search in salsa, see:
https://alioth-lists.debian.net/pipermail/alioth-staff-replacement/Week-of-Mon-20180416/000124.html

**Comment by shanavas786** [comment]
Thanks
