### ISSUE TITLE
npm2deb '@' package name  are failing

### ISSUE THREAD

**Issue by juggernaut451** [LeoIannacone/npm2deb#120]
`npm2deb create @ava/write-file-atomic` will fail. For more details please look at https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=909101

**Comment by maikeueule** [comment]
Hi,

While the fix solves the problem with parsing, the resulting debian/control file is invalid as it contains references like:
    node-@sindresorhus/is (>= 0.11.0)
while packages are named this way:
    node-sindresorhus-is_0.12.0-1_all.deb 

This is one example found when packaging node-got for instance.

**Comment by jani-matti** [comment]
> Hi,
> 
> While the fix solves the problem with parsing, the resulting debian/control file is invalid as it contains references like:
> node-@sindresorhus/is (>= 0.11.0)
> while packages are named this way:
> node-sindresorhus-is_0.12.0-1_all.deb
> 
> This is one example found when packaging node-got for instance.

This issue is still present in 0.3.0. The dependency names are not debianized.
