### ISSUE TITLE
Can npm2deb be used without publishing my package to the registry?

### ISSUE THREAD

**Issue by Denommus** [LeoIannacone/npm2deb#29]
I really didn't understand this from the documentation.

**Comment by shanavas786** [comment]
`npm2deb` never publishes any package to any registry. It helps create debian packages from npm modules.

**Comment by LeoIannacone** [comment]
Hi Denommus!

Can you please elaborate a little bit more? I do not understand what's your use case.

**Comment by LeoIannacone** [comment]
Closing for now.
