### ISSUE TITLE
make npm2deb search smarter

### ISSUE THREAD

**Issue by simevo** [LeoIannacone/npm2deb#32]
If I do:
```
npm2deb search yarn
Looking for similiar package:
  None
...
```
but:
```
apt-get install yarn
Lettura elenco dei pacchetti... Fatto
Generazione albero delle dipendenze       
Lettura informazioni sullo stato... Fatto
Nota, viene selezionato "cmdtest" al posto di "yarn"
```
that's because comdtest `Provides: yarn`

Also it would be super useful if the search command would look for conflicts in terms of installed binaries, something akin to this kind of look-up https://packages.debian.org/search?searchon=contents&keywords=%2Fyarn&mode=path&suite=unstable&arch=any

**Comment by shanavas786** [comment]
`yarn` provided by `cmdtest` and `npm` package are different. The one provided by `cmdtest` is a scenario tester and not a package manager.

**Comment by LeoIannacone** [comment]
I think this is a really edge case. 

Anyway maybe this part can be improved: we could guess if a package ships a "node module" if it depends on nodejs. Does it make sense?

**Comment by shanavas786** [comment]
@LeoIannacone It is not at all a use case. `yarn` provided by `cmdtest` is not an npm module. AFAIK, there is no debian package that ships a node module inside it.

**Comment by LeoIannacone** [comment]
Yeah I know. I was only suggesting to add this check ("if the package depends on nodejs") on the debian search.

Anyway, as you said this is not a issue. Closing :).
