### ISSUE TITLE
node-gyp package not found

### ISSUE THREAD

**Issue by simevo** [LeoIannacone/npm2deb#34]
```
npm2deb depends -b -r yarn
Dependencies:
NPM                                               Debian
yarn (0.16.1)                                     None
...
├─ node-gyp (^3.2.1)                              None
```
but: https://packages.debian.org/sid/node-gyp
this seems weird

**Comment by shanavas786** [comment]
@simevo for an npm module `foo` npm2deb assumes that the debian package is `node-foo` as directed in [debian wiki](https://wiki.debian.org/Javascript/Nodejs/Manual).
`node-gyp` seems to be an exception. Would you care for a PR ?

**Comment by LeoIannacone** [comment]
That's right. This is an exception.

You can add it (see uglifyjs) here: https://wiki.debian.org/Javascript/Nodejs/Database

npm2deb reads that db to handle with these packages.

**Comment by shanavas786** [comment]
Updated the list.

**Comment by simevo** [comment]
this is solved now thanks
