### ISSUE TITLE
use npmjs.com module page as fallback url

### ISSUE THREAD

**Issue by pravi** [LeoIannacone/npm2deb#41]
If a module does not specify a homepage url use npmjs.com/<module name> as homepage in debian/control and Source in debian/copyright

**Comment by shanavas786** [comment]
instead of upstream repo url ? Now hompage falls back to upstream repo url

**Comment by pravi** [comment]
For babel-runtime even that was missing

**Comment by pravi** [comment]
So this would be a fallback if upstream repo url is missing as well.
