### ISSUE TITLE
npm2deb search fails for should

### ISSUE THREAD

**Issue by shanavas786** [LeoIannacone/npm2deb#42]
since source package of `node-should` is `should.js`, `npm2deb search should` fails. [see](https://github.com/LeoIannacone/npm2deb/blob/master/npm2deb/mapper.py#L61).

We may use a mapper like [this](https://wiki.debian.org/Javascript/Nodejs/Database)

**Comment by LeoIannacone** [comment]
Added:
```
    "node-should": {
        "replace": "should.js"
    },
```

**Comment by shanavas786** [comment]
It should have been
```
"should": {
        "replace": "should.js"
    },
```
updated in wiki.

**Comment by LeoIannacone** [comment]
Oh, you're right! Thansk!
