### ISSUE TITLE
handle '.' in package.json correctly

### ISSUE THREAD

**Issue by pravi** [LeoIannacone/npm2deb#44]
Currently npm2deb charm fails because of this section in package.json

```
"directories" : {
        "lib" : ".",
        "example" : "example",
        "test" : "test"
    },
```

This is the error when trying to build,

```
cp: cannot copy a directory, './.', into itself, 'debian/node-charm/usr/lib/nodejs/charm/.'
dh_install: cp --reflink=auto -a ./. debian/node-charm/usr/lib/nodejs/charm// returned exit code 1
debian/rules:8: recipe for target 'binary' failed
```

**Comment by shanavas786** [comment]
It seems to be invalid entry. It should have been `./lib`.

Does npm2deb really need to handle it ?

**Comment by pravi** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA256

shanavas <notifications@github.com> wrote:
> It seems to be invalid entry. It should have been `./lib`.
> 
> Does npm2deb really need to handle it ?
> 

It would be good to ignore such things as a sanity check as I
have seen similar error in other modules too. But its a wishlist,
do it if is not too much work :)

-----BEGIN PGP SIGNATURE-----

iQIzBAEBCAAdFiEEKnl0ri/BUtd4Z9pKzh+cZ0USwioFAliXP9QACgkQzh+cZ0US
wirGEA/9GiFKcDuKDQCDV9kAOGLEO0EQpmPrG3f6HyHSNIQLECTbx6+jccjtlhIX
JMb1cMNzSS9+nus28N7XSruBH0Sk+7u6x62zaoRmGWwIrE/IMs8EcP4i5nz9knkK
1K9FQidJ32eFma0fBhq6HDMMt1Q7E0i+azZoVqgudJ5UqsR5+7hfXqIKaoVcTwbc
rXA97t7Hu0jfvRoIvPUMXA2yrMHHiXFa/whsmjoxTZ1GJJsDvP9vEyQD3v/rtO7T
Mr9xzIBs0OnBZfVQHVY84GWsuWSKr4A8qW58Zf9UX3Bw2RwiTVbCXkYbNq6DFNvL
UO+o2cxXFrY6m5Rx+1bCRxN6ztKiHgAEPhx2jfDd3/kfgnzBxqlqjjQ8wmD8gbSa
oYoCRoFvhRTI6EblNmocozxeqIlym38ALZHBBNcU29NWmMZbKxoNsx9yVkIUO9v9
/2cEpM+vGeS1WPQT/UtJTGh0mjfp9y+vsGb8lN/Z/ECTy84lN0CcTPrQqqKKUvkV
NILkNzwKiAWq+d/4KKcHCZfg3quBL9gfOE1+VWjlzUmPMaSKhiL9acDCgRiAHUYN
i1p5n2zbhDtcm5XrLwE7YNu9n8wTB1VRji0Ajpor1+/m+s/tznkefL5b6eiKOBLn
bA+JyhSCJ87aG/yowZ1cd6kJyEwj0TwZ4AqCgoIsPVxUQVBChMI=
=af5o
-----END PGP SIGNATURE-----
