### ISSUE TITLE
node-lodash-packages has lodash.* modules

### ISSUE THREAD

**Issue by pravi** [LeoIannacone/npm2deb#52]
npm2deb should suggest using node-lodash-packages when looking for lodash.* 

https://wiki.debian.org/Javascript/Nodejs/Database is only for individual packages, a new option to specify wildcards there will also do the job.

**Comment by pravi** [comment]
Like we currently allow,

```
"should": {
        "replace": "should.js"
    },
```

we should allow wild cards like

```
"lodash.*": {
        "replace": "node-lodash-packages"
    },
```

**Comment by shanavas786** [comment]
Isn't mapping `lodash` to `node-lodash-packages`enough.
I could see only a single package in npm registry. Then in which use case `npm2deb` is going to be called with a `lodash/submodule` ?

**Comment by shanavas786** [comment]
Oh, there is a separate npm module for each method. :)

**Comment by shanavas786** [comment]
Please check #56
