### ISSUE TITLE
npm2deb fails with editorconfig

### ISSUE THREAD

**Issue by pravi** [LeoIannacone/npm2deb#61]
$ npm2deb create editorconfig
[Errno 2] No such file or directory: 'package' -> 'editorconfig'

**Comment by shanavas786** [comment]
normally root directory of npm module tarball is named 'package' and it differs for 'editorconfig'

**Comment by pravi** [comment]
@shanavas786 can we report it in editorconfig?

**Comment by pravi** [comment]
but why is it not using the github tarballs?

**Comment by shanavas786** [comment]
> but why is it not using the github tarballs?

For creating debian install files, npm2deb depends on npm2deb tarballs. then after creating debian files it uses watch file to fetch github tarball.

> can we report it in editorconfig?

since npm handles it properly, they need not take it as an issue.
