### ISSUE TITLE
Dependency python3-dateutils is not found

### ISSUE THREAD

**Issue by amruth27m** [LeoIannacone/npm2deb#82]
On running 

> sudo apt-get install devscripts npm python3-dateutil node-github-url-from-git
output
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package python3-dateutils

dateutils must be installed using pip3.

**Comment by shanavas786** [comment]
Are you on Debian ?
https://packages.debian.org/search?keywords=python3-dateutil

**Comment by amruth27m** [comment]
Sorry my machine had some issues with sources.list. It's fine now
