### ISSUE TITLE
npm2deb create @types/jquery fails

### ISSUE THREAD

**Issue by pravi** [LeoIannacone/npm2deb#94]
Even when npm is updated to latest (npm install -g npm), npm2deb fails.

```
praveen@mahishasura:~/forge$ npm2deb view @types/jquery
Name:                                   @types/jquery
Version:                                3.2.16
Description:                            None
Homepage:                               https://npmjs.com/package/@types/jquery
License:                                Expat
Debian:                                 None (None)
praveen@mahishasura:~/forge$ npm2deb create @types/jquery
Error: directory @types/jquery already exists.
praveen@mahishasura:~/forge$ npm --version
5.5.1
```

**Comment by shanavas786** [comment]
npm2deb does not expect / in module name. Please try patch https://github.com/LeoIannacone/npm2deb/pull/96

**Comment by pravi** [comment]
@shanavas786 Now I get
```
praveen@mahishasura:~$ npm2deb create @types/jquery
[Errno 2] No such file or directory: 'jquery' -> '@types/jquery'
```

**Comment by shamlikt** [comment]
@pravi Is this a valid file structure for @types/jquery ? 

@types/
└── jquery
    ├── node-@types-jquery
    │   └── debian
    │       ├── changelog
    │       ├── compat
    │       ├── control
    │       ├── copyright
    │       ├── docs
    │       ├── install
    │       ├── rules
    │       ├── source
    │       │   └── format
    │       ├── tests
    │       │   ├── control
    │       │   └── require
    │       └── watch
    ├── node-@types-jquery-x.x.x
    │   ├── LICENSE
    │   ├── README.md
    │   ├── debian
    │   │   └── Some files
    ├── node-@types-jquery-x.x.x.tar.gz
    ├── node-@types-jquery-x.x.x.debian.tar.xz
    ├── node-@types-jquery-x.x.x.dsc
    ├── node-@types-jquery-x.x.x.orig.tar.gz -> node-@types-jquery-x.x.x.tar.gz
    └── node-@types-jquery_itp.mail

**Comment by pravi** [comment]
@shamlikt package name should be node-types-jquery.

**Comment by shanavas786** [comment]
@pravi @shamlikt updated #96 , please check
