### ISSUE TITLE
use https in watch file when falling back to fakeupstream

### ISSUE THREAD

**Issue by pravi** [LeoIannacone/npm2deb#95]
currently it is http by default

**Comment by simevo** [comment]
perhaps this this addresses by commit https://github.com/LeoIannacone/npm2deb/pull/99/commits/a2489e0a260db46a5298842f637dabbb6d56e928 part of PR #99 ?

**Comment by stultus** [comment]
@pravi I think this issue is fixed. You can close the issue.
