### ISSUE TITLE
Update vcs urls to point to salsa

### ISSUE THREAD

**Issue by pravi** [LeoIannacone/npm2deb#97]
alioth/anonscm is deprecated, newly created packages should point to salsa.debian.org/js-team

**Comment by simevo** [comment]
PR #99 addresses the links, but we should also update the function `search_for_repository`:
https://github.com/LeoIannacone/npm2deb/blob/master/npm2deb/helper.py#L20

**Comment by simevo** [comment]
https://github.com/LeoIannacone/npm2deb/pull/102
